const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),ctx=vm.createContext({module:{exports:{}},console});
for(const file of ['library-config.js','library-core.js','library-files.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx);
const L=ctx.READING_LIBRARY,C=ctx.READING_CONFIG,F=ctx.READING_FILES,id=C.label==='抖音'?'7674938832084569401':'abcDEF12345';
const json=x=>JSON.parse(JSON.stringify(x));
function record(){return L.normalize(id,{title:'采访 / 原话',transcript:[{start:10,text:'你好',speaker:'s1'}],speakerNames:{s1:'主持人'},analysis:{chapters:[{title:'开场',summary:'介绍',timestampSeconds:10}]}},[{id:'n1',videoId:id,text:'我的原话',seconds:12}],C);}
test('library adapts title, time, speaker, notes and overview without mutating sources',()=>{const r=record();assert.equal(r.transcript[0].speakerName,'主持人');assert.equal(r.notes[0].start,12);assert.equal(r.overview.chapters[0].start,10);assert.equal(r.id,id);});
test('library filters settings, keys, jobs and signed media URLs',()=>{const all={secret:'PRIVATE_VALUE',job_foo:{apiKey:'PRIVATE_VALUE'},[C.notesKey]:[],['digest_'+id]:{title:'标题',apiKey:'PRIVATE_VALUE',mediaUrl:'SIGNED_MEDIA',transcript:[{text:'正文',start:0,apiKey:'PRIVATE_VALUE'}]}};const saved=JSON.stringify(L.collect(all,[],C));assert.ok(!saved.includes('PRIVATE_VALUE'));assert.ok(!saved.includes('SIGNED_MEDIA'));assert.ok(saved.includes('正文'));});
test('library retains archived full text after reading cache eviction',()=>{const r=record(),next=L.collect({[C.notesKey]:[]},[r],C)[0];assert.equal(next.transcript[0].text,'你好');assert.equal(next.notes.length,0);});
test('library includes notes-only videos and rejects invalid or missing IDs',()=>{const a=L.collect({[C.notesKey]:[{videoId:id,text:'旧笔记',videoTitle:'旧视频'},{text:'无归属'}]},[],C);assert.equal(a.length,1);assert.equal(a[0].title,'旧视频');for(const bad of [undefined,null,'../escape','x?bad'])assert.equal(L.validId(bad,C),false);});
test('library exports only existing content, not generated placeholder text',()=>{const docs=L.documents(record(),C);assert.deepEqual(json(docs.map(x=>x.name)),['逐字稿','内容概览','我的笔记']);assert.match(docs[0].text,/主持人/);assert.match(docs[0].text,/\[0:10\]/);assert.match(docs[2].text,/我的原话/);});
test('library safely names local folders',()=>{for(const s of ['../a/b','a:b*?','.', 'CON','x\u0000y']){const name=L.filename(s);assert.ok(name.length);assert.ok(!/[<>:"/\\|?*\u0000-\u001f]/.test(name));assert.ok(!/[. ]$/.test(name));}});
test('library sorts cached translations by segment order and excludes unrelated caches',()=>{const r=L.normalize(id,{paragraphCache:{[id+':zh:semantic:segment-3-10000']:'后句',[id+':zh:semantic:segment-1-0']:'前句','foreign:zh:semantic:segment-0-0':'无关'}},[],C);assert.equal(r.translations[0].text,'前句');assert.equal(r.translations[1].start,10);assert.equal(r.translations.length,2);assert.match(L.documents(r,C)[0].text,/不保证覆盖全文/);});
function dir(){const entries=new Map(),children=new Map();return {entries,children,async getDirectoryHandle(n){if(!children.has(n))children.set(n,dir());return children.get(n);},async getFileHandle(n,o={}){if(!entries.has(n)&&!o.create)throw Object.assign(new Error(),{name:'NotFoundError'});if(!entries.has(n))entries.set(n,'');return {getFile:async()=>({text:async()=>entries.get(n)}),createWritable:async()=>{let pending;return {write:async t=>{pending=t;},close:async()=>{entries.set(n,pending);},abort:async()=>{}};}};}};}
test('local saving reuses identical files and preserves edited copies',async()=>{const d=dir();const a=await F.writeUnique(d,'逐字稿','原稿');assert.equal(a.written,true);assert.equal((await F.writeUnique(d,'逐字稿','原稿')).written,false);const b=await F.writeUnique(d,'逐字稿','新稿');assert.equal(b.name,'逐字稿（2）.md');assert.equal(d.entries.get('逐字稿.md'),'原稿');assert.equal(d.entries.size,2);});
test('local saving writes platform/title folders and can be repeated safely',async()=>{const d=dir(),r=record();const first=await F.save(d,[r],C),second=await F.save(d,[r],C);assert.equal(first.saved.length,1);assert.equal(first.written,3);assert.equal(second.written,0);assert.ok(d.children.has(C.label));assert.match(first.saved[0].folder,new RegExp(id));});
test('local saving does not disguise permission or disk errors as success',async()=>{const d={getFileHandle:async()=>{throw Object.assign(new Error('denied'),{name:'NotAllowedError'});}};await assert.rejects(F.writeUnique(d,'逐字稿','x'),/denied/);});
test('entry points and release list include the actual library page',()=>{for(const name of ['options.html','sidepanel.html'])assert.match(fs.readFileSync(path.join(root,name),'utf8'),/href="library.html"/);for(const name of ['library.html','library-core.js','library-db.js','library-files.js','library-config.js','library-background.js','library.js','library.css'])assert.ok(fs.existsSync(path.join(root,name)));assert.match(fs.readFileSync(path.join(root,'background.js'),'utf8'),/importScripts\('library-config.js'/);});
